version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "8086:5000"  # Host port 8086 -> Container port 5000
    environment:
      DOTNET_ENVIRONMENT: Development
