version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "8086:86"  # Host port 8086 -> Container port 86
    environment:
      DOTNET_ENVIRONMENT: Development
