version: '3.9'

services:
  client:
    build:
      context: .            
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "8086:86"          
    environment:
      DOTNET_ENVIRONMENT: Development
    restart: unless-stopped

